name: whitematterlab
favicon: null
layout_spectrum: 0.6222975878044963
typography_spectrum: 0.9341219447087497
title: 'dialogue | change'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8347804995719343
  lightness: 0.6390514362137765
  saturation: 0.03925557108595967
  rhythmicContrast: 0.6858027903363109
purpose: []
